### PR TITLE
Minor changes to work with guzzle 7 + add school specific attendanceCodes endpoint

### PR DESCRIPTION
**Pull request by benlumley**

### CODE REVIEW

**Comment by benlumley** [comment]
See #13 - there are at least 2 others using this code/my repo in production besides me (I use it on two separate projects - one guzzle 6 + 1 guzzle 7)

**Comment by smorris1709** [comment]
any idea when this will be merged in? need to update my guzzle dependency to v7 but this is blocking

**Comment by benlumley** [comment]
> any idea when this will be merged in? need to update my guzzle dependency to v7 but this is blocking

@smorris1709 

no; it's not my repo - the owners/maintainers/wonde seem very quiet.

I've just pulled their commit last month into my fork; so that is up to date with master + then has the updates per the title in this PR.

As above, I'm using the fork in production on 2 projects myself + so are a couple of others.

**Comment by benlumley** [comment]
Master version has implemented this now.

**Pull request closed without merging**
